export const site = {
  name: '공진용 포트폴리오',
  title: '공진용 | AI First Product Engineer 포트폴리오',
  description:
    '2021년부터 FE 개발자로 일했고, 26년 초부터는 AI를 사용한 기획, 디자인, FE(웹/앱), 백엔드 역할을 수행합니다. 5,000개 이상 매장 서비스와 AWS 기반 LLM을 소개합니다.',
  url: (process.env.NEXT_PUBLIC_SITE_URL || 'https://who-is-jinyong-q865.vercel.app').replace(/\/$/, ''),
  locale: 'ko_KR',
  author: '공진용',
  email: 'wlswls8783@gmail.com',
  phone: '+82-10-8981-1131',
  jobTitle: 'AI First Product Engineer',
  company: '메뉴잇',
  github: 'https://github.com/DDooTTaa',
  blog: 'https://ddoottaa.tistory.com/',
  keywords: [
    '공진용',
    '프론트엔드 개발자',
    'AI 개발자',
    'AI First Product Engineer',
    'AI First Front Engineer',
    'React',
    'TypeScript',
    'Next.js',
    'Vue',
    'Flutter',
    '메뉴잇',
  ],
} as const
