export const site = {
  name: '공진용 포트폴리오',
  title: '공진용 | 프론트엔드 · AI 개발자 포트폴리오',
  description:
    '프론트엔드와 AI를 활용해 기획부터 구현까지 빠르게 만드는 개발자 공진용입니다. React, TypeScript, Vue 기반 웹 서비스와 자체 AI 솔루션 경험을 소개합니다.',
  url: (process.env.NEXT_PUBLIC_SITE_URL || 'https://who-is-jinyong.vercel.app').replace(/\/$/, ''),
  locale: 'ko_KR',
  author: '공진용',
  email: 'wlswls8783@gmail.com',
  phone: '+82-10-8981-1131',
  jobTitle: 'Frontend · AI Engineer',
  company: '메뉴잇',
  github: 'https://github.com/DDooTTaa',
  blog: 'https://ddoottaa.tistory.com/',
  keywords: [
    '공진용',
    '프론트엔드 개발자',
    'AI 개발자',
    '프론트엔드 · AI 개발자',
    '포트폴리오',
    'Product Engineer',
    'React',
    'TypeScript',
    'Next.js',
    'Vue',
    'Flutter',
    '메뉴잇',
  ],
} as const
